import 'package:convo_sphere/features/Auth/models/country_model.dart';

class CountryData {

  
 static  List<Country> countries = [
    Country(name: 'Pakistan', isoCode: 'PK', dialCode: '+92', flag: '🇵🇰'),
    Country(name: 'United States', isoCode: 'US', dialCode: '+1', flag: '🇺🇸'),
    Country(name: 'United Kingdom', isoCode: 'GB', dialCode: '+44', flag: '🇬🇧'),
    Country(name: 'India', isoCode: 'IN', dialCode: '+91', flag: '🇮🇳'),
    Country(name: 'Canada', isoCode: 'CA', dialCode: '+1', flag: '🇨🇦'),
    Country(name: 'Australia', isoCode: 'AU', dialCode: '+61', flag: '🇦🇺'),
    Country(name: 'Germany', isoCode: 'DE', dialCode: '+49', flag: '🇩🇪'),
    Country(name: 'France', isoCode: 'FR', dialCode: '+33', flag: '🇫🇷'),
    Country(name: 'Italy', isoCode: 'IT', dialCode: '+39', flag: '🇮🇹'),
    Country(name: 'Spain', isoCode: 'ES', dialCode: '+34', flag: '🇪🇸'),
    Country(name: 'China', isoCode: 'CN', dialCode: '+86', flag: '🇨🇳'),
    Country(name: 'Japan', isoCode: 'JP', dialCode: '+81', flag: '🇯🇵'),
    Country(name: 'South Korea', isoCode: 'KR', dialCode: '+82', flag: '🇰🇷'),
    Country(name: 'Brazil', isoCode: 'BR', dialCode: '+55', flag: '🇧🇷'),
    Country(name: 'Mexico', isoCode: 'MX', dialCode: '+52', flag: '🇲🇽'),
    Country(name: 'Russia', isoCode: 'RU', dialCode: '+7', flag: '🇷🇺'),
    Country(name: 'Saudi Arabia', isoCode: 'SA', dialCode: '+966', flag: '🇸🇦'),
    Country(name: 'United Arab Emirates', isoCode: 'AE', dialCode: '+971', flag: '🇦🇪'),
    Country(name: 'Qatar', isoCode: 'QA', dialCode: '+974', flag: '🇶🇦'),
    Country(name: 'Turkey', isoCode: 'TR', dialCode: '+90', flag: '🇹🇷'),
    Country(name: 'Bangladesh', isoCode: 'BD', dialCode: '+880', flag: '🇧🇩'),
    Country(name: 'Sri Lanka', isoCode: 'LK', dialCode: '+94', flag: '🇱🇰'),
    Country(name: 'Nepal', isoCode: 'NP', dialCode: '+977', flag: '🇳🇵'),
    Country(name: 'Afghanistan', isoCode: 'AF', dialCode: '+93', flag: '🇦🇫'),
    Country(name: 'Indonesia', isoCode: 'ID', dialCode: '+62', flag: '🇮🇩'),
    Country(name: 'Malaysia', isoCode: 'MY', dialCode: '+60', flag: '🇲🇾'),
    Country(name: 'Singapore', isoCode: 'SG', dialCode: '+65', flag: '🇸🇬'),
    Country(name: 'Thailand', isoCode: 'TH', dialCode: '+66', flag: '🇹🇭'),
    Country(name: 'Philippines', isoCode: 'PH', dialCode: '+63', flag: '🇵🇭'),
    Country(name: 'Vietnam', isoCode: 'VN', dialCode: '+84', flag: '🇻🇳'),
    Country(name: 'Egypt', isoCode: 'EG', dialCode: '+20', flag: '🇪🇬'),
    Country(name: 'Nigeria', isoCode: 'NG', dialCode: '+234', flag: '🇳🇬'),
    Country(name: 'South Africa', isoCode: 'ZA', dialCode: '+27', flag: '🇿🇦'),
    Country(name: 'Kenya', isoCode: 'KE', dialCode: '+254', flag: '🇰🇪'),
    Country(name: 'Netherlands', isoCode: 'NL', dialCode: '+31', flag: '🇳🇱'),
    Country(name: 'Belgium', isoCode: 'BE', dialCode: '+32', flag: '🇧🇪'),
    Country(name: 'Switzerland', isoCode: 'CH', dialCode: '+41', flag: '🇨🇭'),
    Country(name: 'Sweden', isoCode: 'SE', dialCode: '+46', flag: '🇸🇪'),
    Country(name: 'Norway', isoCode: 'NO', dialCode: '+47', flag: '🇳🇴'),
    Country(name: 'Poland', isoCode: 'PL', dialCode: '+48', flag: '🇵🇱'),
    Country(name: 'Portugal', isoCode: 'PT', dialCode: '+351', flag: '🇵🇹'),
    Country(name: 'Greece', isoCode: 'GR', dialCode: '+30', flag: '🇬🇷'),
    Country(name: 'Ireland', isoCode: 'IE', dialCode: '+353', flag: '🇮🇪'),
    Country(name: 'New Zealand', isoCode: 'NZ', dialCode: '+64', flag: '🇳🇿'),
    Country(name: 'Iran', isoCode: 'IR', dialCode: '+98', flag: '🇮🇷'),
    Country(name: 'Iraq', isoCode: 'IQ', dialCode: '+964', flag: '🇮🇶'),
    Country(name: 'Jordan', isoCode: 'JO', dialCode: '+962', flag: '🇯🇴'),
    Country(name: 'Kuwait', isoCode: 'KW', dialCode: '+965', flag: '🇰🇼'),
    Country(name: 'Oman', isoCode: 'OM', dialCode: '+968', flag: '🇴🇲'),
    Country(name: 'Bahrain', isoCode: 'BH', dialCode: '+973', flag: '🇧🇭'),
    Country(name: 'Israel', isoCode: 'IL', dialCode: '+972', flag: '🇮🇱'),
    Country(name: 'Ukraine', isoCode: 'UA', dialCode: '+380', flag: '🇺🇦'),
    Country(name: 'Argentina', isoCode: 'AR', dialCode: '+54', flag: '🇦🇷'),
    Country(name: 'Chile', isoCode: 'CL', dialCode: '+56', flag: '🇨🇱'),
    Country(name: 'Colombia', isoCode: 'CO', dialCode: '+57', flag: '🇨🇴'),
  
  ];
}